import Link from '@docusaurus/Link';
import {translate} from '@docusaurus/Translate';
import Layout from '@theme/Layout';
import styles from './index.module.css';

const capabilities = [
  [translate({id: 'homepage.capability.openSource.title', message: 'Open Source'}), translate({id: 'homepage.capability.openSource.description', message: 'The OpenMAVCam software stack is open source and freely available on GitHub—free to use, inspect, and easy to adapt.'}), 'open-source'],
  [translate({id: 'homepage.capability.productionHardware.title', message: 'Production Hardware'}), translate({id: 'homepage.capability.productionHardware.description', message: 'Purpose-built hardware validated through extensive testing for real autonomous missions—not a demo platform.'}), 'production-hardware'],
  [translate({id: 'homepage.capability.camera.title', message: 'Camera'}), translate({id: 'homepage.capability.camera.description', message: 'Full-function camera control: 3A settings, capture, zoom, imaging modes, metadata, photos and video through MAVLink.'}), 'camera-control'],
  [translate({id: 'homepage.capability.ai.title', message: 'AI Function'}), translate({id: 'homepage.capability.ai.description', message: 'Run object detection and tracking directly on the camera platform.'}), 'ai-function'],
  [translate({id: 'homepage.capability.autopilot.title', message: 'Autopilot Compatibility'}), translate({id: 'homepage.capability.autopilot.description', message: 'Automatically adapts to PX4 and ArduPilot without autopilot firmware changes.'}), 'autopilot-compatibility'],
  [translate({id: 'homepage.capability.gimbal.title', message: 'Gimbal Control'}), translate({id: 'homepage.capability.gimbal.description', message: 'Three-axis stabilization and payload pointing with ±0.02° precision through a documented control surface.'}), 'gimbal-control'],
];
const path = [
  [translate({id: 'homepage.path.connect.title', message: 'Connect'}), translate({id: 'homepage.path.connect.description', message: 'Connect your payload.'})],
  [translate({id: 'homepage.path.build.title', message: 'Build'}), translate({id: 'homepage.path.build.description', message: 'Build the image and services.'})],
  [translate({id: 'homepage.path.deploy.title', message: 'Deploy'}), translate({id: 'homepage.path.deploy.description', message: 'Deploy to the target.'})],
  [translate({id: 'homepage.path.integrate.title', message: 'Integrate'}), translate({id: 'homepage.path.integrate.description', message: 'Integrate with your mission stack.'})],
];

export default function Home() {
  return <Layout title={translate({id: 'homepage.meta.title', message: 'Open MAVLink Camera Platform'})} description={translate({id: 'homepage.meta.description', message: 'OpenMAVCam documentation and products'})}><main>
    <section className={styles.hero}><div className={styles.heroContent}><p className={styles.kicker}>{translate({id: 'homepage.kicker', message: 'OPEN MAVLINK CAMERA PLATFORM'})}</p><h1>{translate({id: 'homepage.hero.title', message: 'Open vision for every autonomous mission.'})}</h1><p>{translate({id: 'homepage.hero.description', message: 'Connect camera, AI, video, and gimbal control through one open MAVLink platform.'})}</p><p className={styles.compatibility}>{translate({id: 'homepage.hero.compatibility', message: 'Built for PX4 and ArduPilot — no autopilot firmware changes required.'})}</p><div className={styles.actions}><Link className="button button--primary button--lg" to="/docs/getting-started/build">{translate({id: 'homepage.actions.getStarted', message: 'Get started'})}</Link><Link className="button button--secondary button--lg" to="/docs/products/d64tr">{translate({id: 'homepage.actions.exploreD64TR', message: 'Explore D64TR'})}</Link></div></div></section>
    <section className={styles.featureSection}><div className={styles.sectionIntro}><p className={styles.kicker}>{translate({id: 'homepage.section.whyKicker', message: 'WHY OPENMAVCAM'})}</p><h2>{translate({id: 'homepage.section.whyTitle', message: 'Everything your payload needs, without a closed stack.'})}</h2></div><div className={styles.grid}>{capabilities.map(([title, description, icon]) => <article key={title}><img className={styles.featureIcon} src={`/img/icons/${icon}.svg`} alt="" aria-hidden="true" /><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className={styles.productSection}><div><p className={styles.kicker}>{translate({id: 'homepage.d64tr.kicker', message: 'FEATURED PRODUCT'})}</p><h2>{translate({id: 'homepage.d64tr.title', message: 'D64TR dual-sensor EO/IR gimbal camera'})}</h2><p>{translate({id: 'homepage.d64tr.description', message: '64 MP visible imaging, FLIR Boson+ thermal vision, 15 TOPS edge AI, and a MAVLink-native integration path.'})}</p><Link className="button button--primary" to="/docs/products/d64tr">{translate({id: 'homepage.d64tr.viewSpecs', message: 'View D64TR specifications'})}</Link><div className={styles.productLinks}><Link to="/docs/products/d64tr/build">{translate({id: 'homepage.d64tr.buildImage', message: 'Build image'})}</Link><Link to="/docs/products/d64tr/deploy">{translate({id: 'homepage.d64tr.deployImage', message: 'Deploy image'})}</Link></div></div><img src="/img/products/d64tr/d64tr-on-uav.png" alt={translate({id: 'homepage.d64tr.imageAlt', message: 'D64TR dual-sensor gimbal camera mounted below a multirotor UAV'})} /></section>
    <section className={styles.pathSection}><p className={styles.kicker}>{translate({id: 'homepage.path.kicker', message: 'DEVELOPER PATH'})}</p><h2>{translate({id: 'homepage.path.title', message: 'From camera to mission in four steps.'})}</h2><div className={styles.path}>{path.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
  </main></Layout>;
}
